# Generated by Django 4.2 on 2023-09-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("age", models.IntegerField(default=18)),
                ("sex", models.CharField(max_length=20)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
